### ISSUE TITLE
Just updated Smapi, WaterBot worked for about 4 in-game days, then stopped working mid-field

### ISSUE THREAD

**Issue by Aedronl** [andyruwruw/stardew-valley-water-bot#6]
## Actual behavior: SMAPI says: 
[WaterBot] This mod failed in the Input.ButtonPressed event. Technical details:
System.Exception: Exception of type 'System.Exception' was thrown.
   at StardewValley.PathFindController.findPath(Point startPoint, Point endPoint, isAtEnd endPointFunction, GameLocation location, Character character, Int32 limit) in stardewvalley\Farmer\Farmer\PathFindController.cs:line 189
   at StardewValley.PathFindController..ctor(Character c, GameLocation location, isAtEnd endFunction, Int32 finalFacingDirection, Boolean eraseOldPathController, endBehavior endBehaviorFunction, Int32 limit, Point endPoint, Boolean clearMarriageDialogues) in stardewvalley\Farmer\Farmer\PathFindController.cs:line 133
   at StardewValley.PathFindController..ctor(Character c, GameLocation location, Point endPoint, Int32 finalFacingDirection, endBehavior endBehaviorFunction) in stardewvalley\Farmer\Farmer\PathFindController.cs:line 42
   at WaterBot.Framework.WaterBotControler.start(console console) in C:\Users\andre\source\repos\WaterBot\WaterBot\Framework\WaterBotControler.cs:line 87
   at WaterBot.WaterBot.OnButtonPressed(Object sender, ButtonPressedEventArgs e) in C:\Users\andre\source\repos\WaterBot\WaterBot\ModEntry.cs:line 53
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101

**Comment by Aedronl** [comment]
Reverted to SMAPI 3.18.1 and the WaterBot mod works just fine again. So it is something with the SMAPI 3.18.2 update.
